# Generated by Django 3.2.3 on 2022-02-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
